'https://plantuml.com/sequence-diagram

@startuml
|前置操作|
start
:获取前置任务;
:执行;
|#AliceBlue|填充入参|
:入参构造器;
:执行工具回填;
|#Ivory|快捷调用|
:调用原有接口;
|#WhiteSmoke|后置操作|
:获取后置任务;
:执行;
|#AntiqueWhite|执行结果|
:断言比对结果;
stop

|#Ivory|快捷调用|
start
:展示页面;
:优先展示带占位符的入参;
stop

@enduml