'https://plantuml.com/sequence-diagram
物料工具和用例的执行工具
@startuml
|工具录入|
start
:录入入参;
|#AliceBlue|用例保存|
:保存用例;
|#Ivory|关联关系预设|
:预设动态参数;
|#WhiteSmoke|快捷调用【前端】|
:获取动态参数;
:修改动态参数;
|#AntiqueWhite|快捷调用【后端】执行|
:【前置】、【后置】
、【参数渲染】;
:动作入参渲染;
:执行动作;
stop

@enduml